LIST P=16F887
include "p16f887.inc"
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF
__CONFIG _CONFIG2, _BOR40V & _WRT_OFF
    
  
CONTADOR1 EQU 0x23 
CONTADOR2 EQU 0x24
CONTADOR3 EQU 0x25
 
 
   ORG 0x00
   GOTO _INICIO
 
      ORG 0x05
 
     _INICIO BCF    STATUS, RP1   
             BSF    STATUS, RP0 ; Pasamos al Banco 1
	
	     CLRF TRISC 
	
	BCF    STATUS, RP0    ; Pasamos al Banco 0
        BCF    STATUS, RP1 
	
    RUTINA_PRINCIPAL  MOVLW 0XFF 
    MOVWF CONTADOR1
    MOVWF CONTADOR2
    MOVLW 0X05
    MOVWF CONTADOR3
    
    RETARDO1  DECFSZ CONTADOR1,1 
    GOTO RETARDO1
    MOVLW 0XFF
    MOVWF CONTADOR1
    
    RETARDO2 DECFSZ CONTADOR2,1 
    GOTO RETARDO1 
    MOVLW 0XFF 
    MOVWF CONTADOR2 
    
    RETARDO3 DECFSZ CONTADOR3,1
    GOTO RETARDO1 
    
    BTFSS PORTC,1 
    GOTO _SET
    BTFSC PORTC,1 
    GOTO _RESET 
    
    _RESET BCF PORTC,1 
    GOTO RUTINA_PRINCIPAL 
    _SET BSF PORTC,1 
    GOTO RUTINA_PRINCIPAL 


 END

